#!/usr/bin/env bash
# ============================================================================
# PDF Manager - 本地开发启动脚本 (Bash/Linux/Mac)
# 用法: ./scripts/start.sh
# 作用: 从 .env 读取密钥，生成 Docker 配置，启动服务
# ============================================================================
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT_DIR/.env"
COMPOSE_DIR="$ROOT_DIR/docker/delivery"
WEB_ENV="$COMPOSE_DIR/docker/web.env"
APP_ENV="$COMPOSE_DIR/docker/app.env"
AUTH_JSON="$COMPOSE_DIR/docker/auth.local.json"

# ---- 1. 检查 .env ----
if [ ! -f "$ENV_FILE" ]; then
    echo "[ERROR] .env 文件不存在！请从 .env.example 复制并填入你的密钥:"
    echo "  cp .env.example .env"
    exit 1
fi

# ---- 2. 加载 .env ----
echo "[1/4] 加载 .env 配置..."
set -a
source "$ENV_FILE"
set +a

# ---- 3. 验证 ----
if [ -z "${DEEPSEEK_API_KEY:-}" ]; then
    echo "[ERROR] 缺少 DEEPSEEK_API_KEY — 请在 .env 中设置"
    exit 1
fi
if [ -z "${PADDLE_API_KEY:-}" ]; then
    echo "[ERROR] 缺少 PADDLE_API_KEY — 请在 .env 中设置"
    exit 1
fi

DEEPSEEK_MODEL="${DEEPSEEK_MODEL:-deepseek-v4-flash}"
DEEPSEEK_BASE_URL="${DEEPSEEK_BASE_URL:-https://api.deepseek.com/v1}"
PADDLE_BASE_URL="${PADDLE_BASE_URL:-https://api-m1fbqcjcm3t2tfla.aistudio-app.com/v1}"

# ---- 4. 生成配置 ----
echo "[2/4] 生成 Docker 配置文件..."
cat > "$WEB_ENV" <<WEBEOF
# Generated by start.sh. Do not edit directly.
FRONT_API_BASE=
FRONT_X_API_KEY=${DEEPSEEK_API_KEY}
FRONT_OCR_PROVIDER=paddle
FRONT_PADDLE_TOKEN=${PADDLE_API_KEY}
FRONT_MINERU_TOKEN=
FRONT_MODEL_API_KEY=${DEEPSEEK_API_KEY}
FRONT_MODEL=${DEEPSEEK_MODEL}
FRONT_BASE_URL=${DEEPSEEK_BASE_URL}
WEBEOF

cat > "$APP_ENV" <<APPEOF
# Generated by start.sh. Do not edit directly.
# Core runtime paths
PROJECT_ROOT=/app
RUST_API_ROOT=/app/backend/rust_api
RUST_API_DATA_ROOT=/data
OUTPUT_ROOT=/data/jobs

# Container runtime
PYTHON_BIN=python3
TYPST_BIN=/usr/local/bin/typst
PDF_MANAGER_FONT_PATH=/usr/local/share/fonts/source-han-serif/SourceHanSerifSC-Regular.otf
PDF_MANAGER_TYPST_FONT_FAMILY=Source Han Serif SC

# Container service ports
RUST_API_BIND_HOST=0.0.0.0
RUST_API_PORT=41000
RUST_API_SIMPLE_PORT=42000

# Limits
RUST_API_MAX_RUNNING_JOBS=4
RUST_API_NORMAL_MAX_BYTES=209715200
RUST_API_NORMAL_MAX_PAGES=300

# Provider runtime
RUST_API_KEYS=${DEEPSEEK_API_KEY}
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
DEEPSEEK_MODEL=${DEEPSEEK_MODEL}
RUST_API_DEEPSEEK_BASE_URL=${DEEPSEEK_BASE_URL}
PADDLE_API_KEY=${PADDLE_API_KEY}
RUST_API_PADDLE_BASE_URL=${PADDLE_BASE_URL}
APPEOF

cat > "$AUTH_JSON" <<AUTHEOF
{
  "api_keys": [
    "${DEEPSEEK_API_KEY}"
  ],
  "max_running_jobs": 4,
  "simple_port": 42000
}
AUTHEOF

echo "[3/4] 配置文件已生成"

# ---- 5. 启动 ----
BUILD_FLAG=""
if [ "${1:-}" = "--build" ]; then
    BUILD_FLAG="--build"
fi

echo "[4/4] 启动 Docker 服务..."
docker compose -f "$COMPOSE_DIR/docker-compose.yml" up -d $BUILD_FLAG

echo "[Done] PDF Manager 已启动！"
echo "      前端: http://localhost:40001"
echo "      API:  http://localhost:41000"
