# ============================================================================
# PDF Manager - Local dev startup script (PowerShell)
# Usage: .\scripts\start.ps1
# ============================================================================
param(
    [switch]$Build,
    [switch]$Stop
)

$ErrorActionPreference = "Stop"

$RootDir = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $RootDir ".env"
$ComposeDir = Join-Path $RootDir "docker\delivery"
$ComposeFile = Join-Path $ComposeDir "docker-compose.yml"
$WebEnv = Join-Path $ComposeDir "docker\web.env"
$AppEnv = Join-Path $ComposeDir "docker\app.env"
$AuthJson = Join-Path $ComposeDir "docker\auth.local.json"

if (-not (Test-Path $EnvFile)) {
    Write-Host "[ERROR] .env not found. Copy .env.example to .env first." -ForegroundColor Red
    exit 1
}

Write-Host "[1/4] Loading .env..." -ForegroundColor Cyan
Get-Content $EnvFile | ForEach-Object {
    if ($_ -match "^\s*([^#=]+)=(.+)\s*$") {
        $name = $matches[1].Trim()
        $value = $matches[2].Trim()
        Set-Item "env:$name" $value -ErrorAction SilentlyContinue
    }
}

$required = @{
    DEEPSEEK_API_KEY = "DEEPSEEK_API_KEY"
    PADDLE_API_KEY   = "PADDLE_API_KEY"
}
$missing = $false
foreach ($key in $required.Keys) {
    $current = (Get-Item "env:$key" -ErrorAction SilentlyContinue).Value
    if ([string]::IsNullOrWhiteSpace($current)) {
        Write-Host "[ERROR] Missing $($required[$key]) in .env" -ForegroundColor Red
        $missing = $true
    }
}
if ($missing) { exit 1 }

if ([string]::IsNullOrWhiteSpace($env:DEEPSEEK_MODEL)) {
    $env:DEEPSEEK_MODEL = "deepseek-v4-flash"
}
if ([string]::IsNullOrWhiteSpace($env:DEEPSEEK_BASE_URL)) {
    $env:DEEPSEEK_BASE_URL = "https://api.deepseek.com/v1"
}
if ([string]::IsNullOrWhiteSpace($env:PADDLE_BASE_URL)) {
    $env:PADDLE_BASE_URL = "https://api-m1fbqcjcm3t2tfla.aistudio-app.com/v1"
}

Write-Host "[2/4] Generating Docker config files..." -ForegroundColor Cyan

$webEnvLines = @(
    "# Generated by start.ps1. Do not edit directly."
    "FRONT_API_BASE="
    "FRONT_X_API_KEY=$($env:DEEPSEEK_API_KEY)"
    "FRONT_OCR_PROVIDER=paddle"
    "FRONT_PADDLE_TOKEN=$($env:PADDLE_API_KEY)"
    "FRONT_MINERU_TOKEN="
    "FRONT_MODEL_API_KEY=$($env:DEEPSEEK_API_KEY)"
    "FRONT_MODEL=$($env:DEEPSEEK_MODEL)"
    "FRONT_BASE_URL=$($env:DEEPSEEK_BASE_URL)"
)
$webEnvLines | Set-Content -Path $WebEnv -Encoding Ascii -Force

$appEnvLines = @(
    "# Generated by start.ps1. Do not edit directly."
    "# Core runtime paths"
    "PROJECT_ROOT=/app"
    "RUST_API_ROOT=/app/backend/rust_api"
    "RUST_API_DATA_ROOT=/data"
    "OUTPUT_ROOT=/data/jobs"
    ""
    "# Container runtime"
    "PYTHON_BIN=python3"
    "TYPST_BIN=/usr/local/bin/typst"
    "PDF_MANAGER_FONT_PATH=/usr/local/share/fonts/source-han-serif/SourceHanSerifSC-Regular.otf"
    "PDF_MANAGER_TYPST_FONT_FAMILY=Source Han Serif SC"
    ""
    "# Container service ports"
    "RUST_API_BIND_HOST=0.0.0.0"
    "RUST_API_PORT=41000"
    "RUST_API_SIMPLE_PORT=42000"
    ""
    "# Limits"
    "RUST_API_MAX_RUNNING_JOBS=4"
    "RUST_API_NORMAL_MAX_BYTES=209715200"
    "RUST_API_NORMAL_MAX_PAGES=300"
    ""
    "# Provider runtime"
    "RUST_API_KEYS=$($env:DEEPSEEK_API_KEY)"
    "DEEPSEEK_API_KEY=$($env:DEEPSEEK_API_KEY)"
    "DEEPSEEK_MODEL=$($env:DEEPSEEK_MODEL)"
    "RUST_API_DEEPSEEK_BASE_URL=$($env:DEEPSEEK_BASE_URL)"
    "PADDLE_API_KEY=$($env:PADDLE_API_KEY)"
    "RUST_API_PADDLE_BASE_URL=$($env:PADDLE_BASE_URL)"
)
$appEnvLines | Set-Content -Path $AppEnv -Encoding Ascii -Force

$authObject = @{
    api_keys = @($env:DEEPSEEK_API_KEY)
    max_running_jobs = 4
    simple_port = 42000
}
$authObject | ConvertTo-Json -Depth 4 | Set-Content -Path $AuthJson -Encoding Ascii -Force

Write-Host "[3/4] Config files generated" -ForegroundColor Cyan

if ($Stop) {
    Write-Host "[4/4] Stopping services..." -ForegroundColor Cyan
    & docker compose -f $ComposeFile down
    Write-Host "[Done] Services stopped" -ForegroundColor Green
    return
}

Write-Host "[4/4] Starting Docker services..." -ForegroundColor Cyan
$composeArgs = @("compose", "-f", $ComposeFile, "up", "-d")
if ($Build) {
    $composeArgs += "--build"
}
& docker @composeArgs

if ($LASTEXITCODE -eq 0) {
    Write-Host "[Done] PDF Manager started" -ForegroundColor Green
    Write-Host "      Frontend: http://localhost:40001" -ForegroundColor Green
    Write-Host "      API:      http://localhost:41000" -ForegroundColor Green
} else {
    Write-Host "[ERROR] Startup failed. Check Docker status and logs." -ForegroundColor Red
    exit 1
}
